<?xml version="1.0" encoding="utf-8"?><Database Name="SisApp" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-031NGTQ;Initial Catalog=SisApp;Persist Security Info=True;User ID=sa" SettingsObjectName="SisApp.Properties.Settings" SettingsPropertyName="SisAppConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cliente" Member="Cliente">
    <Type Name="Cliente">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cedula" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Cliente_Venta" Member="Venta" ThisKey="Id" OtherKey="ClienteId" Type="Venta" />
    </Type>
  </Table>
  <Table Name="dbo.Categoria" Member="Categoria">
    <Type Name="Categoria">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Categoria_Producto" Member="Producto" ThisKey="Id" OtherKey="CategoriaId" Type="Producto" />
    </Type>
  </Table>
  <Table Name="dbo.VentaProducto" Member="VentaProducto">
    <Type Name="VentaProducto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VentaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Producto" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ValorUnidad" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ValorTotal" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="Venta_VentaProducto" Member="Venta" ThisKey="VentaId" OtherKey="Id" Type="Venta" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Producto_VentaProducto" Member="Producto1" ThisKey="ProductoId" OtherKey="Id" Type="Producto" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Venta" Member="Venta">
    <Type Name="Venta">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClienteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaId" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TotalFactura" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SubTotal" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Iva" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Descuento" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Efectivo" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Cambio" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CajaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Venta_VentaProducto" Member="VentaProducto" ThisKey="Id" OtherKey="VentaId" Type="VentaProducto" />
      <Association Name="Cliente_Venta" Member="Cliente" ThisKey="ClienteId" OtherKey="Id" Type="Cliente" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Caja_Venta" Member="Caja" ThisKey="CajaId" OtherKey="Id" Type="Caja" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Caja" Member="Caja">
    <Type Name="Caja">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NombreCaja" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="Departamento" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AlmacenId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Caja_Venta" Member="Venta" ThisKey="Id" OtherKey="CajaId" Type="Venta" />
      <Association Name="Almacen_Caja" Member="Almacen" ThisKey="AlmacenId" OtherKey="Id" Type="Almacen" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Roles">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Rol" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AlmacenProducto" Member="AlmacenProducto">
    <Type Name="AlmacenProducto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AlmacenId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Stock" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ValorUnidad" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Almacen_AlmacenProducto" Member="Almacen" ThisKey="AlmacenId" OtherKey="Id" Type="Almacen" IsForeignKey="true" />
      <Association Name="Producto_AlmacenProducto" Member="Producto" ThisKey="ProductoId" OtherKey="Id" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Almacen" Member="Almacen">
    <Type Name="Almacen">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Almacen" Member="Almacen1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Ruc" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TelefonoDos" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Almacen_Caja" Member="Caja" ThisKey="Id" OtherKey="AlmacenId" Type="Caja" />
      <Association Name="Almacen_AlmacenProducto" Member="AlmacenProducto" ThisKey="Id" OtherKey="AlmacenId" Type="AlmacenProducto" />
    </Type>
  </Table>
  <Table Name="dbo.Producto" Member="Producto">
    <Type Name="Producto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Producto" Member="Producto1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoriaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrecioCompra" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CodigoBarra" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Producto_VentaProducto" Member="VentaProducto" ThisKey="Id" OtherKey="ProductoId" Type="VentaProducto" />
      <Association Name="Producto_AlmacenProducto" Member="AlmacenProducto" ThisKey="Id" OtherKey="ProductoId" Type="AlmacenProducto" />
      <Association Name="Categoria_Producto" Member="Categoria" ThisKey="CategoriaId" OtherKey="Id" Type="Categoria" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>